### ISSUE TITLE
Error when I search for dark mode. Started happening after I uninstalled a version of Python 3.11 and kept just 3.7, I think

### ISSUE THREAD

**Issue by g-adel** [Garulf/windows-dark-mode-toggle#5]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True
```
Python Path: C:\Users\Jimmy\AppData\Local\Programs\Python\Python37-32\pythonw.exe
Node Path: 
Date: 03/03/2023 10:49:45
Exception:
Windows Dark Mode Toggle Exception: 
Websites: https://github.com/Garulf/windows-dark-mode-toggle
Author: Garulf
Version: 1.0.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Jimmy\AppData\Roaming\FlowLauncher\Plugins\Windows Dark Mode Toggle-1.0.3\run.py", line 9, in <module>
    from plugin.windows_dark_mode_toggle import WindowsDarkModeToggle
  File "C:\Users\Jimmy\AppData\Roaming\FlowLauncher\Plugins\Windows Dark Mode Toggle-1.0.3\plugin\windows_dark_mode_toggle.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\Jimmy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\Jimmy\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Jimmy\AppData\Roaming\FlowLauncher\Plugins\Windows Dark Mode Toggle-1.0.3\run.py", line 9, in <module>
    from plugin.windows_dark_mode_toggle import WindowsDarkModeToggle
  File "C:\Users\Jimmy\AppData\Roaming\FlowLauncher\Plugins\Windows Dark Mode Toggle-1.0.3\plugin\windows_dark_mode_toggle.py", line 4, in <module>
    from flox import Flox
  File "C:\Users\Jimmy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\Jimmy\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by Garulf** [comment]
This plugin uses a feature introduced in Python 3.8. 

Please use Python 3.8 and your issue should fix itself.
